import "../styles/main.scss";
import "../styles/second.scss";
import "../styles/training.scss";
import "../styles/sport.scss";
import "../styles/football.scss";
import "../styles/images_gallery.scss";
import "./form.js";
import "./animate.js";
import "./dropdown.js";